### PR TITLE
Issue #84: Update repo for easier development.

### PR DESCRIPTION
**Pull request by BWPanda**
Fixes https://github.com/backdrop-ops/api.backdropcms.org/issues/84

### CODE REVIEW

**Comment by jenlampton** [comment]
Accidentally closed.

**Comment by jenlampton** [comment]
Looks like this PR has a conflict, can you please rebase?

**Comment by BWPanda** [comment]
@jenlampton Hope I did that right...

**Comment by jenlampton** [comment]
looks good :)

**Pull request merged**
